=head1 NAME

pachooks - sample hooks for libalpm/pacman

=head1 DESCRIPTION

=over

=item check-boot - check that /boot is mounted before trying to modify it

=item check-license - warn if a package with an unapproved license is installed

=item check-mount - check that necessary devices are mounted

=item check-suid - print post-install warnings for suid/getcap binaries

=item fc-cache - rebuild system font information cache

=item info-install, info-remove - update info file database

=item mkfontscale-otf, mkfontscale-ttf - update X11 font name files

=item snapshot-pre-btrfs, snapshot-post-btrfs - take btrfs snapshots

=item snapshot-pre-snapper, snapshot-post-snapper - take filesystem snapshots

=item sync - sync storage caches to reduce the risk of file system corruption

=item update-desktop-database - update cache databse for F<.desktop> files

=back

=head1 HOOKS vs INSTALL SCRIPTS

Hooks and scripts each fill a different packaging niche.  Install scripts are
included directly in the package that runs them and are run immediately prior
to installation or removal of the package.  Hooks may be provided by any
package, not necessarily the one(s) that trigger it, or the user and are run
before or after the transaction.  Hooks are generally preferable for any tasks
that need to be repeated for a number of packages.  Any essential tasks (e.g.
rebuilding the initramfs after a kernel update) should either be run in
a C<PreTransaction> hook or continue to use an install script due to the risk
of post-transaction hooks not running if the transaction is interrupted.

=head1 FILES

=over

=item F</usr/share/alpm/hooks.bin/> - executables to be used by hooks

=item F</usr/share/alpm/hooks.local/> - inactive hooks for users to enable

=back

=head1 COPYRIGHT AND LICENSE

Copyright 2015 Andrew Gregory <andrew.gregory.8@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

=head1 SEE ALSO

L<alpm-hooks(5)>
