=head1 NAME

pachooks - sample hooks for libalpm/pacman

=head1 SYNOPSIS

As of version 5.0 pacman's libalpm has support for user-provided hooks to run
before or after transactions.  These hooks and accompanying scripts are
intended to showcase the power and flexibility of this feature as well as serve
as examples for how to write hooks.

=head1 DESCRIPTION

=over

=item check-boot - check that /boot is mounted before trying to modify it

=item check-suid - print post-install warnings for suid/getcap binaries

=item sync - sync storage caches to reduce the risk of file system corruption

=back

=head1 COPYRIGHT AND LICENSE

Copyright 2015 Andrew Gregory <andrew.gregory.8@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
