#!/bin/bash

configfile="/etc/pachooks/check-mount"

mountpoints=()

if ! [ -f "$configfile" ]; then
    printf "error: missing configuration file '%s'\n" "$configfile"
    exit 1
fi

ret=0
for mp in "${mountpoints[@]}"; do
    if ! findmnt "$mp" &>/dev/null; then
        printf "error: '%s' not mounted\n" "$mp"
        ret=1
    fi
done
exit $ret
